# -*- coding: utf-8 -*-
"""A2 AI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_yJJ91Y_LN524SOD79bBpBlYtO6qvuSu

## Import Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

"""## Preprocessing"""

data = pd.read_csv('AI DATA.csv')

data.head()

data.shape

year = data['Year'].unique()

year

for i in range(0, len(year)):
  data.loc[data["Year"] == year[i], "Year"] = i

data.head()

county = data['County'].unique()

county

for i in range(0, len(county)):
  data.loc[data["County"] == county[i], "County"] = i

data.head()

months = data['Month'].unique()

months

for i in range(0, len(months)):
  data.loc[data["Month"] == months[i], "Month"] = i + 1

data.head()

species = data['Species'].unique()

species

for i in range(0, len(species)):
  data.loc[data["Species"] == species[i], "Species"] = i

data.head()

actions = data['Action'].unique()

for i in range(0, len(actions)):
  data.loc[data["Action"] == actions[i], "Action"] = i

data.head()

"""## Creating of Dataset"""

input_data = data[['Year', 'County', 'Month', 'Species']]

label_data = data[['Action']]

input_data.shape

label_data.shape

train_X, test_X, train_Y, test_Y = train_test_split(input_data, label_data, test_size=0.3, random_state=1)

train_X.shape

train_Y = train_Y['Action'].tolist()

test_Y = test_Y['Action'].tolist()

test_X.shape

"""## Training and Testing of Model"""

model = GaussianNB()

model.fit(train_X, train_Y)

pred_Y = model.predict(test_X)

pred_Y

test_Y

from sklearn.metrics import classification_report

print(classification_report(test_Y, pred_Y))